author:
  name: Shubhom Srivastava
  role: Backend Engineer @ Hornet
  bio: Backend Engineer specializing in distributed systems and high-throughput event-driven architectures.
  location: Delhi, India

social:
  - id: "github"
    label: "GitHub"
    href: "https://github.com/Shbhom"
  - id: "linkedin"
    label: "Linkedin"
    href: "https://linkedin.com/in/shubhom-srivastava"
  - id: "email"
    label: "Email"
    href: "mailto:shbhomsrivastav@gmail.com"